name: bakir

on:
  push:
    branches: [ main, dev ]

jobs:
    ime-posla:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: list-files
          run: ls -la

    ime-drugog-posla:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: print
          run: echo "Lint ok"

        