name: bakir

on:
  push:
    branches: [ main, dev ]

jobs:
    ime-posla:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: list-files
          run: ls -la

    ime-drugog-posla:
        runs-on: ubuntu-latest

        steps:
        - uses: actions/checkout@v4

        - name: print
          run: echo "Lint ok"

    build-zip:
        runs-on: ubuntu-latest
        
        steps:
        - uses:  actions/checkout@v4

        - name: crate-zip
          run: |
            mkdir -p test-files
            echo "Hello 1" > test-files/test1.txt
            echo "Hello 2" > test-files/test2.txt
            zip -r test.zip test-files/ 

        - name: Upload artifact
          uses: actions/upload-artifact@v3
          with:
            name: test-zip
            path: test.zip
    use-zip:
        runs-on: ubuntu-latest
        needs: build-zip
        steps: 
        - uses: actions/download-artifact@v3 
          with:
            name: test-zip 
        - name: List files 
          run: ls -la
